spring:
  profiles:
    active: demo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis-plus-ext?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroLongTimeBehavior=convertToNull
    username: root
    password: 12345678

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl